### ISSUE TITLE
include api 

### ISSUE THREAD

**Issue by walterchang** [DECENTfoundation/DCorePHP-SDK#28]
Hi,

I tried to include DcoreApi into my webpage as below, 

```php
include_once $_SERVER['DOCUMENT_ROOT'].'/dcorephp-sdk/src/DCoreApi.php';
include_once $_SERVER['DOCUMENT_ROOT'].'/dcorephp-sdk/src/DCoreSdk.php';
$dcoreApi = new \DCorePHP\DCoreApi(
    'https://testnet-api.dcore.io/',
    'wss://testnet-api.dcore.io'
);
```

But get the error log on this, please advice, thank you.

```
PHP Fatal error:  Class 'DCorePHP\\DCoreSdk' not found in /var/www/html/dcorephp-sdk/src/DCoreApi.php on line 31
```

**Comment by ttibensky** [comment]
Hi,

I don't think it will work with using `include_once`. Our library is using [namespaces](https://www.php.net/manual/en/language.namespaces.php).

Using namespaces, it would look like in one of our [examples](https://github.com/DECENTfoundation/DCore-SDK-Examples/tree/master/sdk-php). Lets look at the beginning of [php script file](https://github.com/DECENTfoundation/DCore-SDK-Examples/blob/master/sdk-php/src/CreateAccount.php) which is supposed to create a new account in DCORE:

```php
<?php

require dirname(__DIR__).'/vendor/autoload.php';

use DCorePHP\DCoreApi;
use DCorePHP\Model\ChainObject;

$dcoreApi = new DCoreApi(
    'https://testnet-api.dcore.io/',
    'wss://testnet-api.dcore.io',
    true // @todo set to false in production environment
);

...
```

I would suggest you to install the sdk from [packagist](https://packagist.org/packages/decentfoundation/dcorephp-sdk) using [composer](https://getcomposer.org/) which will create an [autoloader](https://www.php.net/manual/en/language.oop5.autoload.php) class for you (this handles all the includes and namespaces for you).

If you are new to this topic, I would suggest to start looking at the following [composer basics](https://getcomposer.org/doc/01-basic-usage.md). Doing following google searches might help you get to it:
- "php namespace"
- "how does php namespace work"
- "php autoloader"
- "how does php autoloader work"
- "how to install php library using composer"
- "how to install php library using packagist"

You can also look at our our [README.md](https://github.com/DECENTfoundation/DCorePHP-SDK#requirements) which describes the dependencies and also contains installation instructions. 

Thank you for your time to bring up your problem, we will try to make our README file more understandable. Please let us know if any of this helps. I will close this issue for the moment as it doesn't address any problem with the library itself.

**Comment by walterchang** [comment]
Hi,

Thank you for response and information. Actually I did read the README.md
and followed the instructions. I done the installation successfully but
failed in Dcore API initialization. Due to i just wanna use your api for my
application so i wouldn't read your codes in detail. That's easy for us if
the instructions of README getting more detail.

I have tried again as your instructions below to apply api, but not work,
still need your suggestions,

--Config
<?php
require $_SERVER['DOCUMENT_ROOT'].'/DcorePHP/vendor/autoload.php';

use DcorePHP\DCoreApi;
use DcorePHP\Model\ChainObject;

$dcoreApi = new DCoreApi(
    'https://testnet-api.dcore.io/',
    'wss://testnet-api.dcore.io',
true // @todo set to false in production environment
);
?>


--Error Log
[Fri May 31 15:21:08.080095 2019] [php7:error] [pid 28667] [client
223.136.159.128:51497] PHP Fatal error:  Uncaught Error: Class
'DcorePHP\\DCoreApi' not found in
/var/www/html/wp-content/themes/ecommerce-shop/dctapi.php:7\nStack
trace:\n#0
/var/www/html/wp-content/themes/ecommerce-shop/woocommerce/myaccount/dctinfo.php(2):
include_once()\n#1
/var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(249):
include('/var/www/html/w...')\n#2
/var/www/html/wp-content/themes/ecommerce-shop/functions.php(267):
wc_get_template('myaccount/dctin...')\n#3
/var/www/html/wp-includes/class-wp-hook.php(286):
dctinfo_endpoint_content('')\n#4
/var/www/html/wp-includes/class-wp-hook.php(310):
WP_Hook->apply_filters('', Array)\n#5
/var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)\n#6
/var/www/html/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3004):
do_action('woocommerce_acc...', '')\n#7
/var/www/html/wp-includes/class-wp-hook.php(286):
woocommerce_account_content('')\n#8
/var/www/html/wp-includes/class-wp-hook.php(310):
WP_Hook->apply_filters(NULL, Array)\n#9 /var/www/html/wp-includes/ in
/var/www/html/wp-content/themes/ecommerce-shop/dctapi.php on line 7,
referer: https://n1.sslab.giize.com/dctec/my-account/decent-info/


it seems getting better than previous status.......
Please have your comments .

Regards,
Walter

Tomáš Tibenský <notifications@github.com> 於 2019年5月30日 週四 下午8:15寫道：

**Comment by walterchang** [comment]
Hi again,

thank you first for suggestions. I already call api and got the response successfully. Now I would like to get the value for the api response. I tried many times in different methods (preg_split,json_decode,json_encode,get_object_value...), but it can't get the value within the assigned key. below is the  config & result, pls have your comments. Thanks a lot.

config:
$account = $dcoreApi->getAccountApi()->getByName('example-account-1559320974');
var_dump(get_object_vars($account));

result:
string(78) "request: {"jsonrpc":"2.0","id":1,"method":"call","params":[1,"login",["",""]]}" string(32) "response: {"id":1,"result":true}" string(76) "request: {"jsonrpc":"2.0","id":2,"method":"call","params":[1,"database",[]]}" string(29) "response: {"id":2,"result":6}" string(115) "request: {"jsonrpc":"2.0","id":3,"method":"call","params":[6,"get_account_by_name",["example-account-1559320974"]]}" string(764) "response: {"id":3,"result":{"id":"1.2.655","registrar":"1.2.27","name":"example-account-1559320974","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["DCT6TjLhr8uESvgtxrbWuXNAN3vcqzBMw5eyEup3PMiD2gnVxeuTb",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["DCT6TjLhr8uESvgtxrbWuXNAN3vcqzBMw5eyEup3PMiD2gnVxeuTb",1]]},"options":{"memo_key":"DCT6TjLhr8uESvgtxrbWuXNAN3vcqzBMw5eyEup3PMiD2gnVxeuTb","voting_account":"1.2.3","num_miner":0,"votes":[],"extensions":[],"allow_subscription":false,"price_per_subscribe":{"amount":0,"asset_id":"1.3.0"},"subscription_period":0},"rights_to_publish":{"is_publishing_manager":false,"publishing_rights_received":[],"publishing_rights_forwarded":[]},"statistics":"2.5.655","top_n_control_flags":0}}" array(0) { }

**Comment by iammatis** [comment]
Hey, I'm glad you worked out the previous problem. Seems like you've got the debug mode on (because of the `string(xy)` outputs), but other than that, your code seems to be working fine. From the debug, you can see that `Dcore`, returned the desired account: 
`string(764) "response: {"id":3,"result":{"id":"1.2.655","registrar":"1.2.27","name":"example-account-1559320974","owner"...`

So your account is now an [Account Object](https://github.com/DECENTfoundation/DCorePHP-SDK/blob/master/src/Model/Account.php) in the `$account` variable. You can call the available `getters` on it, or simply `dump($account)` it.
